### PR TITLE
Missing the support to stream datatype for scalcout records

### PR DESCRIPTION
**Pull request by douglasbeniz**
Hello Han!

I'was compiling a IOC with a DataBase defining DTYP as "stream" to an scalcout Record and it was not supported by StreamDevice installed using e3.

After doing what I'm proposing at this PullRequest and recompile the module it is working now.

Do you think it makes sense, Han?

If it does, it is necessary to modify anything at https://github.com/paulscherrerinstitute/StreamDevice?

Thank you!
/ Douglas B Beniz

### CODE REVIEW

**Comment by jeonghanlee** [comment]
~~Which StreamDevice do you use? StreamDevice at PSI doesn't support scalcout record.~~
I found this. But I have to check it first. If this is option, so I would like to add this support to the option, not to the default one.  I will propose a slight different later.

**Comment by jeonghanlee** [comment]
BTW, which stream version which you use, it looks like you don't use the 2.7.14p. I've checked 2.7.14p doesn't have scalcout record support yet.

**Comment by douglasbeniz** [comment]
I found this at https://github.com/paulscherrerinstitute/StreamDevice/commit/90a6fd4af9fd6cb04b46959d4889e3544d620b59#diff-30013a4b617f9015d0816f6311e49ab3 which is supposed to be at *stream_2_7_14* version.

```
# Do you have synApps and want support for scalcout?
# Then define CALC or SYNAPPS in your RELEASE file
# pointing to the 'calc' module of synApps.
# Due to strange cross dependencies in synApps
# you have to build the 'sscan' and 'genSub'
# modules before building 'calc'.
# See doc/scalcout.html for a required fix in scalcout.
SYNAPPS_RECORDS += scalcout
```

And this at https://github.com/paulscherrerinstitute/StreamDevice/commit/31189ebecf384538366d2558359d091787abbcdf#diff-30013a4b617f9015d0816f6311e49ab3 which is supposed to be at *2.8.8* version.

```
# Due to strange cross dependencies in synApps
# you have to build the 'sscan' and 'genSub'
# modules before building 'calc'.
# The 'calc' version must be 2-4 or higher.
# Up to version 2-6 (synApps 5.1) the 'calc' module needs a fix.
# See doc/scalcout.html for details.
ifneq ($(words $(CALC) $(SYNAPPS)), 0)
RECORDTYPES += scalcout
endif
```

So, officially supported StreamDevice version by e3 is stream_2_7_4? Fine, what should I do to compile an IOC (made by someone else that I'm supposed to "just integrate" at official ICS EPICS setup) which database requires a "stream" data-type into a "scalcout" record?

Thank you for your time!

/ Douglas

**Comment by jeonghanlee** [comment]
@douglasbeniz , I may miss something. I will check them again. Maybe we enable that support by default for next release. If there is a request to upgrade the stream version of this. I am willing to update the stream module version to match the request. you can use your hacked version until I will implement.

**Comment by douglasbeniz** [comment]
Thank you, @jeonghanlee! For while I can use it, no problem, but, it has other weird dependencies with that IOC I showed you personally... probably the better is to refactor it! I'll discuss with the guys here and I'll ask your help if necessary!

Since it has a planned update to fully support 2.8.8 version of StreamDevice (or later), I'm happy if you decide to close this PR. Thanks!

Cheers!

/ Douglas

**Comment by jeonghanlee** [comment]
@douglasbeniz , f7a297b has the 2.8.8 with calc support. There will be few minors changes. But it should be no problem at all.  Now, it will be more robust to add support records and I also add lsi/lso support either. If you are OK with this, can you cancel this pull request?

**Comment by douglasbeniz** [comment]
I've tested it, the modification setting 2.8.8 as the default version for StreamDevice, and it worked perfectly for me, @jeonghanlee! 

Thank you!

**Comment by douglasbeniz** [comment]
Since the update to support v2.8.8 as default fits my requirements, I'm cancelling the PR.

**Pull request closed without merging**
